# Generated by Django 5.1.7 on 2025-11-10 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('quotation', 'Quotation'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='bills/%Y/%m/')),
                ('file_hash', models.CharField(blank=True, max_length=66)),
                ('ai_verified', models.BooleanField(default=False)),
                ('ai_confidence', models.IntegerField(default=0)),
                ('ai_analysis', models.TextField(blank=True)),
                ('ai_extracted_amount', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('ai_warnings', models.JSONField(default=list)),
                ('ai_recommendations', models.TextField(blank=True)),
                ('authority_approved', models.BooleanField(default=False)),
                ('approved_by', models.CharField(blank=True, max_length=42)),
                ('approval_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending AI Verification'), ('verifying', 'AI Verification in Progress'), ('verified', 'AI Verified'), ('failed', 'AI Verification Failed'), ('approved', 'Authority Approved'), ('rejected', 'Authority Rejected')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_id', models.IntegerField(unique=True)),
                ('description', models.TextField()),
                ('recipient_address', models.CharField(max_length=42)),
                ('total_amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('state', models.IntegerField(choices=[(0, 'Created'), (1, 'UnderAuthorityVoting'), (2, 'PublicVoting'), (3, 'Approved'), (4, 'Rejected'), (5, 'InProgress'), (6, 'Completed')], default=0)),
                ('authority_yes_votes', models.IntegerField(default=0)),
                ('authority_no_votes', models.IntegerField(default=0)),
                ('public_yes_votes', models.IntegerField(default=0)),
                ('public_no_votes', models.IntegerField(default=0)),
                ('current_stage', models.IntegerField(default=0)),
                ('total_stages', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField()),
                ('confidence', models.IntegerField()),
                ('analysis', models.TextField()),
                ('extracted_amount', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('warnings', models.JSONField(default=list)),
                ('processing_time', models.FloatField()),
                ('model_used', models.CharField(default='gpt-4o', max_length=50)),
                ('api_cost', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='APIs.bill')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='APIs.proposal'),
        ),
        migrations.CreateModel(
            name='ProposalStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('state', models.IntegerField(choices=[(0, 'NotStarted'), (1, 'InProgress'), (2, 'Completed')], default=0)),
                ('report', models.TextField(blank=True)),
                ('ai_report', models.TextField(blank=True)),
                ('vote_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='APIs.proposal')),
            ],
            options={
                'ordering': ['stage_number'],
                'unique_together': {('proposal', 'stage_number')},
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='APIs.proposalstage'),
        ),
    ]
